-- Data gathered from https://en.wikipedia.org/wiki/List_of_restaurant_chains_in_the_United_States
-- Restaurant data
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Salt Lake County', 0.18, 0.9, 'Cupbop', 0.59, 'Utah', 'F6I 2D0');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Quezon City', 4.61, 2.53, 'Jollibee', 0.17, 'Philippines', 'N4Z 6K4');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Honolulu', 3.94, 1.09, 'L&L Hawaiian Barbecue', 2.26, 'Hawaii', 'L7H 7O3');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Peterborough', 3.95, 0.75, 'Manchu Wok', 1.07, 'Ontario', 'U1H 8M0');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Denver', 1.85, 4.04, 'Noodles & Company', 0.86, 'Colorado', 'F8U 5Z8');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Glendale', 1.16, 3.98, 'Panda Express', 3.38, 'California', 'P5X 5X7');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Scottsdale', 2.21, 0.17, 'Pei Wei Asian Diner', 0.95, 'Arizona', 'M0F 3P1');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('San Jose', 1.97, 2.59, 'Phở Hòa', 4.13, 'California', 'I6W 7T7');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Rancho Santa Margarita', 0.38, 1.56, 'Pick Up Stix', 1.21, 'California', 'K7Q 8P9');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Boston', 1.43, 3.12, 'Sarku Japan', 4.2, 'Massachusetts', 'C8L 9D6');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Tokyo', 0.41, 0.46, 'Yoshinoya', 2.79, 'Japan', 'U2G 3K9');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Cincinnati', 3.98, 3.74, 'Gold Star Chili', 1.21, 'Ohio', 'O4Q 9E9');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('McDonough', 4.78, 2.6, 'Shane''s Rib Shack', 2.68, 'Georgia', 'E1F 9V7');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Cincinnati', 3.59, 4.89, 'Skyline Chili', 1.97, 'Ohio', 'G1H 7H9');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Chicago', 3.9, 3.4, 'Argo Tea', 2.16, 'Illinois', 'T5L 7H9');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('East Lansing', 0.38, 4.17, 'Biggby Coffee', 2.57, 'Michigan', 'X1A 7D3');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Portland', 4.42, 3.25, 'Black Rock Coffee Bar', 1, 'Oregon', 'W1J 5E2');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Edina', 0.32, 3.02, 'Caribou Coffee', 2.24, 'Minnesota', 'Y9Z 4H2');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Los Angeles', 1.79, 1.36, 'The Coffee Bean & Tea Leaf', 2.69, 'California', 'V4N 7N6');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Dearborn', 0.05, 4.26, 'Coffee Beanery', 4.66, 'Michigan', 'Z8H 5Q0');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Quincy', 2.89, 1.46, 'Dunkin'' Donuts', 1.28, 'Massachusetts', 'H4M 8B4');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Saint Paul', 1.68, 0.73, 'Dunn Brothers Coffee', 3.29, 'Minnesota', 'U2S 6Z2');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Grants Pass', 0.33, 2, 'Dutch Bros. Coffee', 3, 'Oregon', 'B2N 4G2');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Long Grove', 4, 0.75, 'Gloria Jean''s Coffees', 0.64, 'Illinois', 'V0U 5R2');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('New York', 2.33, 2.08, 'Gregorys Coffee', 0.34, 'New York', 'O0F 1G2');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Louisville', 3.98, 2.44, 'Heine Brothers''', 2.79, 'Kentucky', 'E7D 9Z0');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Chicago', 4.93, 2.54, 'Intelligentsia Coffee & Tea', 3.64, 'Illinois', 'B2G 1Y1');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('San Luis Obispo', 3.49, 4.78, 'Jamba Juice', 4.57, 'California', 'B2X 8T0');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Brea', 2.75, 0.64, 'Juice It Up!', 0.22, 'California', 'S1H 7Q1');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Los Angeles', 2.53, 3, 'Orange Julius', 4.38, 'California', 'F5H 5X1');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Berkeley', 1.2, 2.03, 'Peet''s Coffee', 1.1, 'California', 'P0C 2I2');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('San Francisco', 4.55, 4.42, 'Philz Coffee', 1.94, 'California', 'W6A 5Q8');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Atlanta', 2.37, 4.84, 'Planet Smoothie', 1.67, 'Georgia', 'K2Q 5C8');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Los Angeles', 0.15, 1.97, 'Robeks', 1.48, 'California', 'W7C 2X3');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Seattle', 1.22, 2.6, 'Seattle''s Best Coffee', 3, 'Washington', 'X1E 4I6');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Kenner', 0.76, 4.12, 'Smoothie King', 1.73, 'Louisiana', 'G8F 3P6');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Seattle', 2.85, 1.15, 'Starbucks', 3.65, 'Washington', 'G1S 1T7');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Hamilton', 3.7, 3.82, 'Tim Hortons', 2.51, 'Ontario', 'Q4H 8X3');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Destin', 3.78, 2.41, 'Tropical Smoothie Cafe', 0.99, 'Florida', 'D5Q 0I3');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Charlotte', 0.44, 2.44, 'Bojangles'' Famous Chicken ''n Biscuits', 1.01, 'North Carolina', 'T2F 9G7');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Bridgeview', 0.2, 1.54, 'Brown''s Chicken & Pasta', 3.34, 'Illinois', 'D5Q 0I3');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Newton', 1.09, 1.75, 'Boston Market', 1.02, 'Massachusetts', 'T2F 9G7');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Waco', 4.45, 3.98, 'Bush''s Chicken', 3.95, 'Texas', 'G7R 7V6');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Birmingham', 2.18, 3.14, 'Chester''s International', 2.92, ' Alabama', 'G3G 0F1');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Hapeville', 3.58, 2.52, 'Chick-fil-A', 3.36, 'Georgia', 'S2T 7V4');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Benbrook', 1.24, 2.93, 'Chicken Express', 2.8, 'Texas', 'J8M 8I4');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('San Antonio', 0.08, 2.37, 'Church''s Chicken', 0.49, 'Texas', 'K7I 0K3');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('New Brunswick', 1.95, 4.59, 'Cluck-U Chicken', 4.94, 'New Jersey', 'Z8A 7B8');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Guasave', 4.38, 2.28, 'El Pollo Loco', 2.32, 'Sinaloa', 'E5Y 5M0');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('San Marcos', 3.26, 0.75, 'Golden Chick', 2.37, 'Texas', 'M7C 0B0');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Haleyville', 3.55, 3.52, 'Guthrie''s', 1.26, 'Alabama', 'X5E 2Z8');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Spring', 1.12, 4.19, 'Hartz Chicken', 2.94, '	Texas', 'C1P 8D8');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('North Corbin', 3.88, 3.98, 'KFC', 1.32, 'Kentucky', 'K6B 1D7');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Lima', 1.13, 4.89, 'Lee''s Famous Recipe Chicken', 0.24, 'Ohio', 'R6K 4D6');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Los Angeles', 4.54, 1.23, 'Louisiana Famous Fried Chicken', 3.66, 'California', 'F1B 5A1');
INSERT INTO RESTAURANTS (CITY, DAIRY, EGG, NAME, PEANUT, STATE, ZIPCODE) VALUES ('Mississauga', 4.5, 4.74, 'Shawarma Royale', 0.56, 'Ontario', 'J0G 7P2');


-- User data
INSERT INTO resturant_USERS (CITY, DAIRY, EGG, PEANUT, NAME, STATE, ZIPCODE) VALUES ('Milton', false, false, false, 'Sceptres', 'Ontario', 'S5D 6A4')